[package]
name = "rest_rocket"
version = "0.1.0"
edition = "2024"

[dependencies]
clippy = "0.0.302"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
